// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCE4cEz06NdxnsOuArWBwE5WHiC-fiqHo',
    appId: '1:95107159948:web:8f436ca43f6469ae2e28a9',
    messagingSenderId: '95107159948',
    projectId: 'fests-3bc00',
    authDomain: 'fests-3bc00.firebaseapp.com',
    storageBucket: 'fests-3bc00.appspot.com',
    measurementId: 'G-T6B6EMY058',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk_hpH9b5m7m5bIvTJIl6EHGfxXakgf5w',
    appId: '1:95107159948:android:091dc81da6510c972e28a9',
    messagingSenderId: '95107159948',
    projectId: 'fests-3bc00',
    storageBucket: 'fests-3bc00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZiKhKMqWUEf3FDcYG9jEIeE7zKoQawUk',
    appId: '1:95107159948:ios:b806b86e4fbc9a0b2e28a9',
    messagingSenderId: '95107159948',
    projectId: 'fests-3bc00',
    storageBucket: 'fests-3bc00.appspot.com',
    iosBundleId: 'com.nithish.fests',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZiKhKMqWUEf3FDcYG9jEIeE7zKoQawUk',
    appId: '1:95107159948:ios:6a133b1e1b2c66f42e28a9',
    messagingSenderId: '95107159948',
    projectId: 'fests-3bc00',
    storageBucket: 'fests-3bc00.appspot.com',
    iosBundleId: 'com.nithish.fests.RunnerTests',
  );
}
